databases:
  - name: you_payment_budget_app
    databaseName: you_payment_budget_app
    user: you_payment_budget_app_user

services:
  - type: web
    name: budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: you_payment_budget_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false